params:
  K: 8
  alpha: 0.1
  beta_end_value: 0.01
  beta_n_iterations: 4000
  beta_start_iteration: 0
  beta_start_value: 1
  delta_d: 0.1
  dual: true
  gene_dim: 50
  head_num: 1
  hidden_dim: 64
  lr: 0.001
  method: euler
  optimizer_name: NAdam
  std_seq: 0.1
  std_x: 0.014
  std_y: 0.014
  std_z: 0.1
  stride: 1
  warm_up_rate: 0.0001
  weight_decay: 1.0e-08
trainer: IsoST


