params:
  K: 8
  _lambda_1: 1000
  _lambda_2: 0.0001
  alpha: 0.1
  beta_end_value: 0.001
  beta_n_iterations: 8000
  beta_start_iteration: 8000
  beta_start_value: 1
  delta_d: 0.01
  gene_dim: 50
  head_num: 1
  hidden_dim: 64
  image_data_dir: data/CCFv3_feature
  lr: 0.001
  method: euler
  optimizer_name: NAdam
  scale_z: 1
  slice_data_dir: data/zhuang_ABCA_3
  slice_width: 0.2
  spacing:
  - 0.01
  - 0.01
  - 0.01
  std_seq: 0.1
  std_x: 0.01
  std_y: 0.01
  std_z: 0.057
  stride: 1
  template_sample_rate: 0.125
  warm_up_rate: 0.01
  weight_decay: 1.0e-08
trainer: IsoSTImageReg

